### ISSUE TITLE
Allow Credentials for use cases that use @dhis2/app-runtime

### ISSUE THREAD

**Issue by nnkogift** [hisptz/dhis2-mediator#10]
- By default app platform assumes it connects directly to DHIS2, making it send its requests with `credentials` set to true. When using this mode, the mediator throws a CORS error due to the header mismatch. Consider adding the setup
 - 
 ```
  app.enableCors({
       ...other setup,
        credentials: true
    });
  ```
To allow the mediator to process runtime requests

**Comment by ericchingalo** [comment]
This is already fixed
